"""empty message

Revision ID: 091d9010a4e5
Revises: 
Create Date: 2018-03-18 22:20:22.253094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091d9010a4e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarifario',
    sa.Column('id_tarifa', sa.Integer(), nullable=False),
    sa.Column('data_inicial', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('valor_diaria', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_tarifa')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('data_checkin', sa.Date(), nullable=True),
    sa.Column('data_checkout', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('valor_final', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('usuarios')
    op.drop_table('tarifario')
    # ### end Alembic commands ###
