"""empty message

Revision ID: 4304f2963e10
Revises: 7210fac85003
Create Date: 2018-03-25 03:08:56.226017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4304f2963e10'
down_revision = '7210fac85003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos',
    sa.Column('id_codigo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_codigo'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigos')
    # ### end Alembic commands ###
