"""empty message

Revision ID: 52326b02602b
Revises: 
Create Date: 2018-03-25 01:52:06.401236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52326b02602b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.Integer(), nullable=True))
    op.drop_column('usuarios', 'password2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###
