"""empty message

Revision ID: 7210fac85003
Revises: 52326b02602b
Create Date: 2018-03-25 01:54:12.695859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7210fac85003'
down_revision = '52326b02602b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###
